require('./lib/empleado')
require('./lib/generador_cheque')
require('./lib/cheque')
require('./lib/sindicato')
require('./lib/tarjeta_de_servicio')
require('./lib/tarjeta_de_tiempo')
require('./lib/clasificador_por_hora')
require('./lib/clasificador_salario_fijo')
require('./lib/contrato_mensual')
require('./lib/contrato_quincenal')
require('./lib/contrato_trimestral')
require('./lib/repositorio_empleado')
require('./lib/repositorio_cheques')
require('./lib/repositorio_sindicato')
require('./lib/persistencia_json')
require('./lib/persistencia_memoria')
require 'date'